Repository esfiddle/site, pull requests merged in 2019-10, with the labels that each got.

#68 Update ISSUE_TEMPLATE.md to include more information
  .github/ISSUE_TEMPLATE.md
Labels: :rocket: enhancement

#73 :rocket: Issue 63 create light and dark themes
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  public/img/favicon.ico
  public/index.html
  src/components/Header/Header.vue
  src/store.js
  src/views/About.vue
  src/views/Blog.vue
  src/views/Editor.vue
  src/views/Examples.vue
Labels: :rocket: enhancement

#74 :rocket: Issue 65 implement firebase with authentication
  package.json
  src/components/Authentication/Login/Login.vue
  src/components/Authentication/Login/LoginButton/LoginButton.vue
  src/components/Authentication/Signup/Signup.vue
  src/components/Button/Button.vue
  src/components/Footer/Footer.vue
  src/components/Header/Header.vue
  src/components/Profile/Profile.vue
  src/firestore.js
  src/main.js
  src/router.js
  yarn.lock
Labels: :rocket: enhancement

#77 Adjust CONTRIBUTE.md to show proper labels
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CONTRIBUTE.md
Labels: :wrench: maintenance

#79 :wrench: Adjust the docs to be more in line with the project vision
  .github/issue-branch.yml
  .github/release-drafter.yml
  docs/CONTRIBUTE.md
  docs/CONTRIBUTORS.md
  docs/FAQ.md
  docs/REPORTBUG.md
  docs/VISION.md
Labels: :wrench: maintenance

#81 :wrench: More docs maintenance
  CONTRIBUTING.md
Labels: :wrench: maintenance

#84 :wrench: Docs maintenance
  README.md
Labels: :wrench: maintenance

#85 :memo: Additional docs maintenance
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/REPORTBUG.md
Labels: :memo: documentation

#92 :memo: Docs maintenance
  README.md
Labels: :memo: documentation

#97 🐛Remove broken style guide link in README.md #3
  README.md
Labels: :memo: documentation

#98 :rocket: Issue 75
  package.json
  src/components/Authentication/Login/Login.vue
  src/components/Authentication/Login/LoginButton/LoginButton.vue
  src/components/Button/Button.vue
  src/components/Header/Header.vue
  src/components/Landing/Hero/Hero.vue
  src/components/Profile/Profile.vue
  src/router.js
  src/store.js
  yarn.lock
Labels: :rocket: enhancement
